### ISSUE TITLE
[April 14 - April 27] Engage with contributors

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/feluda#270]
Help the contributors identify problem statement and their chosen approach. Setup a regular way to interacti with them

**Comment by dennyabrain** [comment]
I've replied to the contributors telling them how to proceed.
https://github.com/tattle-made/feluda/issues/82#issuecomment-2058794148 and https://github.com/tattle-made/feluda/issues/81#issuecomment-2058795839

**Comment by aatmanvaidya** [comment]
this is now being tracked here - https://github.com/tattle-made/feluda/issues/278
closing this issue
