### ISSUE TITLE
[Apr 28 - May 11] Engage with contributors

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#278]
Help the contributors identify problem statement and their chosen approach. Setup a regular way to interact with them

**Comment by aatmanvaidya** [comment]
A contributors work on clustering videos is being tracked here - https://github.com/tattle-made/feluda/issues/277

**Comment by Aryankb** [comment]
@dennyabrain @aatmanvaidya 
I was trying to set up feluda in my local system. After cloning the repo in a conda environment, I ran all the commands, moved the docker files - **Dockerfile.vid_vec_rep_resnet** and **Dockerfile.image_vec_rep_resnet** to **src**, changed the paths in the docker files accordingly. Created  the doker containers,All commands were executed successfully, but the last command **docker exec -it feluda_api python server.py** was unable to execute. there was an error stating **cv2 not found** regardless of the presence of **opencv-python-headless** in the **vid_vec_rep_resnet_requirements.txt** file whose contents were installed earlier. When i manually installed it in feluda_api container, then next time it showed scipy not found. it means that the contents of vid_vec_rep_resnet_requirements.txt are not getting located by feluda_api. **I want to ask do i need to create an additional docker file for the creation of container feluda_api** ?
![Screenshot from 2024-05-22 21-42-46](https://github.com/tattle-made/feluda/assets/118632488/9de4a7a6-5f65-4f09-ae0d-ec9dbb51c30f)

**Comment by aatmanvaidya** [comment]
Hi @Aryankb, which installation instructions did you follow? was it the setup guide on the Wiki - https://github.com/tattle-made/feluda/wiki/Setup-Feluda-Locally

So when you do `docker-compose up`, what the base `Dockerfile` will do is just install some core requirements of Feluda and might not have operator specific requirements installed. For example the video operator (vid_vec_rep_resnet.py) requires `torch` and `cv2`, that won't be installed. 

so for installing operator specific requirements, you can follow the instructions [here](https://github.com/tattle-made/feluda/wiki/Setup-Feluda-Locally#step-4---installing-packages-for-operators).
1. exec into the docker container 
```sh
docker exec --user python feluda_api /bin/sh
```
2. then install requirements for that operator
```sh
cd core/operators
pip install --require-hashes --no-deps -r vid_vec_rep_resnet_requirements.txt
```
So install the libraries inside the docker image itself

and now if you run `python server.py` from inside the docker container, that should work!

please let me know if I can help out in any other way!

**Comment by Aryankb** [comment]
@aatmanvaidya
Thankyou for the guidance. I followed the installation instructions given in the readme file previously. Now it is working fine. But now the localhost:7000 is not getting loaded. What could be the reason?

**Comment by aatmanvaidya** [comment]
Hi, @Aryankb, I think `localhost:7000` not getting loaded in a known issue to us, it has to do with some `flask` package updates. We will fix it soon, regardless, since Feluda is a backend engine, there is no UI as such, so even if `localhost:7000` won't load, you will still be able to use the server
