### ISSUE TITLE
Extraction of unique keyframes from video

### ISSUE THREAD

**Issue by Aryankb** [tattle-made/feluda#287]
### Ticket Contents
Related to #81 
@dennyabrain 
I was exploring the ways to extract unique frames from the video. I tried to extract unique keyframes from some videos using **ffmpeg** - to extract keyframes from the video and **k-means**- to extract unique keyframes from keyframes extracted by ffmpeg, and here are the results :-  

(We can select  **one image from each cluster**, as the **representation of that cluster**, then further we can use some image captioning models to generate **small captions for each image**. Next we can **combine all captions to generate the final caption** for the video or use them to classify the video accurately.)

[Google Collab Notebook ](https://colab.research.google.com/drive/1fA6TonJ-YAMYBufPXcwg7q_B5EoCnV3Y?usp=sharing)

**Video Link** : https://drive.google.com/file/d/1Qr08m4Bf0JjTszExDLoey2LCqcJjJl3n/view?usp=drive_link
**Clusters** :
![image](https://github.com/tattle-made/feluda/assets/118632488/bee88049-a955-4c7a-aafb-2262a45a0f5c)
![image](https://github.com/tattle-made/feluda/assets/118632488/874c9205-0f76-4f89-97d6-b1103021f335)
![image](https://github.com/tattle-made/feluda/assets/118632488/398f761e-1cd0-4ffe-a6cc-f7bebb49ff78)

****Video 2 link** : https://drive.google.com/file/d/1QnupjsK7ILQUYrqlPT2pTdTAzoy8Wi-C/view?usp=drive_link
Clusters** : 
![image](https://github.com/tattle-made/feluda/assets/118632488/dfe73bee-b5a2-4c4a-8c42-ac5033ad949e)
![image](https://github.com/tattle-made/feluda/assets/118632488/46a8aafc-2856-490c-a3d6-ad3298967add)
![image](https://github.com/tattle-made/feluda/assets/118632488/34e05f5b-38f7-4542-a34a-0f2c30f1b81d)

I'll be now working on ways to cluster the images such that it selects the no. of clusters automatically,  Please give your reviews and directions for the future work. 

### Goals

(We can select  **one image from each cluster**, as the **representation of that cluster**, then further we can use some image captioning models to generate **small captions for each image**. Next we can **combine all captions to generate the final caption** for the video or use them to classify the video accurately.)

### Implementation Details

**ffmpeg** - to extract keyframes from the video and **k-means**- to extract unique keyframes from keyframes extracted by ffmpeg

### Product Name

Feluda

### Organisation Name

Tattle

### Domain

⁠Learning & Development

### Tech Skills Needed

Computer Vision

### Category

Machine Learning

**Comment by dennyabrain** [comment]
@Aryankb thanks for the work. I didn't know you could use ffmpeg itself to extract keyframes. Can you help me understand what exactly the select parameter do in ffmpeg? I see the following query in your notebook `"select=eq(pict_type\,I)"`
I referred to the ffmpeg documentation for select parameter here - https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect where there is this explanation
```
pict_type (video only)
    The type of the filtered frame. It can assume one of the following values:
    I
    P
    B
    S
    SI
    SP
    BI
```

but what do the various values - I,P,B,S etc mean? can you link us to the documentation for that?

**Comment by Aryankb** [comment]
@dennyabrain 
The I, P, B, etc. are the types of frames of a video, used for video compression. I have extracted I - Frames from the video. Particularly, I-Frames: The Anchors of Accuracy:  also known as “Intra-frames,” are complete frames that contain all the visual information necessary for accurate rendering. These frames act as anchor points for decoding and are independent of other frames. Please refer to this [documentation](https://ottverse.com/i-p-b-frames-idr-keyframes-differences-usecases/) for a deep dive into types of frames.

**Comment by Aryankb** [comment]
@dennyabrain 
Simpler explaination of I -Frames and it's alternatives : [link](https://medium.com/@publiciscommerce/extracting-i-frames-keyframes-from-a-video-using-ffmpeg-cb7f2ae3add1)

**Comment by Snehil-Shah** [comment]
@dennyabrain @Aryankb This approach looks pretty neat. 

I tried comparing the results with our current approach and a *shot transition detection* approach. In more detail in [Notebook](https://colab.research.google.com/drive/18sG-NVTXAnJO0wHNFJtD5IOu3MSqlvC8?usp=sharing)
 
I used @Aryankb 's video sample and ran it through 3 different approaches to extract 5 unique keyframes. I didn't use ffmpeg for aryan's approach instead just used KMeans clustering on keyframes extracted using Feluda's current approach

**Currently implemented approach in Feluda**:

![image](https://github.com/tattle-made/feluda/assets/130062020/15813449-a8b3-4f87-beb7-c95175c1bc38)

**Clustering approach**:

![image](https://github.com/tattle-made/feluda/assets/130062020/783712c9-0e43-4405-87c5-4ea1768e65eb)

**Shot transition detection**: As there aren't really many transitions, there are less unique frames.

![image](https://github.com/tattle-made/feluda/assets/130062020/09c5ccc8-b992-4cb0-8df9-f88ff52c15a0)

**My thoughts**:

- The current approach of QR decomposition works surprisingly well and isn't really *naive*.
- The clustering approach works great as it's able to find frames all belonging to different clusters.
- This video doesn't have definitive transitions. It's a smooth panoramic shot. Hence shot transition detection isn't the most ideal approach here IMO.

**Comment by dennyabrain** [comment]
Very interesting and obvious conclusion that the shot transition method obviously works better on videos that are "edited" and have many shots and not as well on smooth camera panning videos.

In our use case we would actually have both type of video. For instance I ran ffmpeg with the select filter on a vlog with meme reaction, and it did a great job in extracting just the right key frames.
![Frame 2(1)](https://github.com/tattle-made/feluda/assets/1415361/f7f4662a-c1cc-421f-b22a-d2e7ce7bba73)

We also sometimes get videos that are just amateur recordings taken from a phone camera so thats a use case worth considering as well. 

I'm getting a little greedy here but I wonder if we could do both to cover most use cases and optionally, add a step to separate out any redundant frames and only store vectors for the remaining "unique" keyframes.

**Comment by Snehil-Shah** [comment]
@dennyabrain Aryan's approach should cover both the use cases.
Just to be clear, the core idea of Aryan's approach isn't ffmpeg. It just extracts keyframes. The core idea is clustering the keyframes to basically find the *k farthest neighbours* where k is the number of frames we are taking average of to construct the final video vector (5 in current Feluda implementation).
Ofcourse as @Aryankb mentioned, finding a way that dynamically finds the number of clusters will give us more efficient results. Say a video is just a photo for 5 seconds, we would just get 1 cluster and we would just use that 1 frame to generate the final embedding.

**Comment by Aryankb** [comment]
@dennyabrain I wanted to ask did you use the following select filter approach or used the previous I -Frame approach ?

![image](https://github.com/tattle-made/feluda/assets/118632488/df559b24-d9ba-4a08-be07-72e6b00515ed)

Also, as you mentioned, we have both kinds of videos, "multiple transitions" and "smooth camera recordings." what we can do is I'll try the above select filter approach for camera recordings and compare the results by (I- frame) + (k means clustering) approach. If we get good results, we can go ahead with the select filter approach only, else we'll use the I-Frames approach to select the keyframes, then we'll use clustering methods to cluster them and take 1 frame from each cluster. This way, the redundant frames will be removed. Also, we can decide the optimal no. of clusters using the **Elbow method** or the **Silhouette method**.

Also, @Snehil-Shah Thanks for the detailed comparisons.

Sorry for the delay due to end sem exams. I'll post the new notebook soon.

**Comment by dennyabrain** [comment]
@Aryankb I should have clarified. I used "select=gt(scene\,0.1)". My understanding is that it selects frames that are 0.1 % different from precending frame. Although I'm not sure how its defining "different".

**Comment by dennyabrain** [comment]
I should also mention that we are not adamant on using 5 frames to represent a video. That total number of frames can be whatever gives us good results. In fact I am guessing its best if its atleast proportionate to video length. Atleast in our current phase we want to make sure we can capture all "keyframes" in a video, even if at the cost of higher storage requirements. Of course we'd like if we don't have to save 100 frames for a 5 second videos, so any optimization on that end is appreciated.

**Comment by Snehil-Shah** [comment]
@dennyabrain @Aryankb Well, didn't know ffmpeg was this powerful! 😅

**Comment by dennyabrain** [comment]
haha thats kind of what what led to this tweet today - https://twitter.com/tattlemade/status/1786614237449842794

**Comment by Snehil-Shah** [comment]
> I should have clarified. I used "select=gt(scene,0.1)". My understanding is that it selects frames that are 0.1 % different from precending frame. Although I'm not sure how its defining "different".

@dennyabrain isn't this the same as shot transition detection?

**Comment by dennyabrain** [comment]
To my understanding yes, but I am not sure of the implementation details on what exactly FFMPEG is doing here. I just found about this on the blog Aryan listed, read about this on the FFMPEG documentation and tried by running it on some files I have. Unfortunately their documentation doesn't tell a lot about how something works. So you might need to do your own research.

**Comment by Aryankb** [comment]
@dennyabrain @Snehil-Shah 
According to some experiments, i think that it just compares the next frame with the previous frame. If there is >= x % change in the next frame, it extracts that frame. This is working very well for edited videos if we give x = 30 %. But it is unable to extract a single frame from smooth camera recordings. For camera recordings, we need to give x = 5 %.

**Comment by Aryankb** [comment]
@dennyabrain 
I think the best we can do is to use the "I - Frames" approach. It handles this problem very well. It extracts the no. of frames according to the length and changes in the video. This is the updated notebook in which i have automated the whole process :-
[Notebook](https://colab.research.google.com/drive/1fA6TonJ-YAMYBufPXcwg7q_B5EoCnV3Y?usp=sharing)
- **Keyframe Extraction.**
- **Finding the optimal no of clusters using the silhoutte scores.**
- Extracting the no of images from each cluster **prooportional to the size of cluster,** so that we dont miss any keyframe (due to clustering errors).
- **Generate captions for each unique keyframe** using caption generation model trained on the Coco 2017 dataset.. (IN KAGGLE NOTEBOOK). (I tried downloading the model , but it was not working, maybe because some functions and parameters used while training the model were not getting downloaded with the model. For using this model, we need to download the dataset of 27 GB, train the model, and deploy in the cloud to use it remotely.)
![Screenshot 2024-05-07 184347](https://github.com/tattle-made/feluda/assets/118632488/f2d6be11-b86d-4bbd-ac61-4348d4804266)
![Screenshot 2024-05-07 184334](https://github.com/tattle-made/feluda/assets/118632488/65ee1c69-d882-43db-afb7-f3df55a44fbc)

While passing the new video, just change the variable "Fol = Name of new folder". Folder will get created if not exists. Then pass the video path in the variable "command" , and run all the cells. The unique keyframes will be saved in the folder unique_keyframe inside the folder created above.

This is the [google drive link](https://drive.google.com/drive/folders/1Qn6lKHBCnBGYcQT_i4cWCmTz5DzfFU5R?usp=sharing) which contains some youtube shorts (30 - 60 sec) and videos (10 - 15 minutes).

**Comment by Aryankb** [comment]
@dennyabrain 
Then, we can get the most occurring Meaning in the captions using LDA topic modeling -> [notebook ](https://colab.research.google.com/drive/1JrPFRC2gphkZN1NkuDErDaeyUAymMw1J?usp=sharing)

![Screenshot 2024-05-07 190020](https://github.com/tattle-made/feluda/assets/118632488/6599d0e9-b4e7-4b0d-9ace-27febafed470)

![Screenshot 2024-05-07 190028](https://github.com/tattle-made/feluda/assets/118632488/9ac2ae2e-b027-43d5-bc78-1b46e3c31971)

**Comment by aatmanvaidya** [comment]
closing this issue because the DMP program has started.
