### ISSUE TITLE
[May 12 - May 25] Review DMP proposals for Feluda

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#310]

**Comment by dennyabrain** [comment]
Once the interviews are done, we'll share the result here and close it.

**Comment by Aryankb** [comment]
@dennyabrain ara all interviews over? Were there any screening before interviews?

**Comment by dennyabrain** [comment]
@Aryankb yes we had shortlisted some candidates and interviewed them. the interviews are over. the C4GT team would be announcing the results shortly.
