### ISSUE TITLE
Operator to detect language in an Audio file

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#316]
Operators are core components of Feluda, they are modules that help us analyse media items - text, image, video, audio etc. All the code for operators can be found at `src/core/operators`

The task is to create a Operator that can **detect language** in a Audio media item. This is an open ended issue, you will have to investigate on what methods to do this are best and effective. 
For now the operator should be able to identify/detect the `English`, `Hindi`, `Telugu` and `Tamil` languages. 

## Expected Outcome
- Write an operator, profile it for RAM and CPU usage. A key outcome should be that the operator should have stabilised RAM usage. Some methods on profiling have been documented on the Wiki [here](https://github.com/tattle-made/feluda/wiki/Optimization).
- Write a test for the operator
- Document the operator on the Wiki

**Comment by Snehil-Shah** [comment]
@aatmanvaidya can I work on this?

**Comment by aatmanvaidya** [comment]
Hi @Snehil-Shah , there is a similar issue for video's as well - https://github.com/tattle-made/feluda/issues/319
are you interested in picking that up? or else this audio one is also fine!

**Comment by Snehil-Shah** [comment]
@aatmanvaidya This is fine. Can I be assigned?

**Comment by Snehil-Shah** [comment]
### Operator profile

| Audio Length | CPU Time (s) | RAM Usage |
|---|---|---|
| 10s | 1.61 | 214.0MiB |
| 30s | 2.33 | 215.8MiB |
| 1m | 3.46 | 218.6MiB |
| 5m | 12.14 | 275.8MiB |
| 10m | 23.20 | 550.6MiB |
| 30m | 66 | 1.6GiB |

**Comment by aatmanvaidya** [comment]
This issue has been resolved here - https://github.com/tattle-made/feluda/pull/324
