### ISSUE TITLE
Operator to detect language in a Video file

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#319]
Operators are core components of Feluda, they are modules that help us analyse media items - text, image, video, audio etc. All the code for operators can be found at `src/core/operators`

The task is to create a Operator that can **detect language** in a **Video** media item. This is an open ended issue, you will have to investigate on what methods to do this are best and effective. 
For now the operator should be able to identify/detect the `English`, `Hindi`, `Telugu` and `Tamil` languages. 

## Expected Outcome
- Write an operator, profile it for RAM and CPU usage. A key outcome should be that the operator should have stabilised RAM usage. Some methods on profiling have been documented on the Wiki [here](https://github.com/tattle-made/feluda/wiki/Optimization).
- Write a test for the operator
- Document the operator on the Wiki

**Comment by plon-Susk7** [comment]
Hi, I'd love to work on this.

**Comment by aatmanvaidya** [comment]
hi @plon-Susk7 please feel free to take it up!

**Comment by aatmanvaidya** [comment]
@plon-Susk7 whenever you get time, do add the profiling results here
