### ISSUE TITLE
Write Test for Queue [RabbitMQ]

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#320]
Feluda relies on tests to make sure each component if functioning properly. It help us ensure code reliability and test expected behaviour.

All the tests can be found at `src/tests/` folder. The documentation for running the tests can be found on the Wiki [here](https://github.com/tattle-made/feluda/wiki/Test-and-Benchmark) and [here](https://github.com/tattle-made/feluda?tab=readme-ov-file#running-tests) 

The task is to write a test for `RabbitMQ` to test the connection and creation of `queues`. 

## Expected Outcome
- write a test in this folder location - `src/tests/queue/`
- The test should connect to the `RabbitMQ` and check if all the queues are being created properly.

**Comment by plon-Susk7** [comment]
Hey Aatman,

Can I take up this issue?

**Comment by aatmanvaidya** [comment]
hi @plon-Susk7, please feel free to take it up!

**Comment by plon-Susk7** [comment]
Hey @aatmanvaidya, I was trying to setup the project on my local system. I tried to follow the readme but there's no path src/api/operators. Is this a typo?

**Comment by aatmanvaidya** [comment]
hi @plon-Susk7, actually the instructions are on the wiki here - https://github.com/tattle-made/feluda/wiki/Setup-Feluda-Locally

We will fix the readme to point to the correct instructions, my bad

**Comment by plon-Susk7** [comment]
Hey @aatmanvaidya I had to specify following commands to run the test. I hope this might help to update the documentation.

```bash
export PYTHONPATH=/usr/app:$PYTHONPATH
```

**Comment by aatmanvaidya** [comment]
> Hey @aatmanvaidya I had to specify following commands to run the test. I hope this might help to update the documentation.
> 
> ```shell
> export PYTHONPATH=/usr/app:$PYTHONPATH
> ```

Hi @plon-Susk7 - where did you have to run the export command? or did you have to add it in the Dockerfile?

Also if you exec into the container as a python user, then you might not face this issue
while testing out the PR - https://github.com/tattle-made/feluda/pull/400, this is what I had done to run the test
```sh
docker-compose up
# next, in a new terminal
docker exec --user python -it feluda_api /bin/sh
# now inside the feluda_api container
python -m unittest tests.queue.test_rabbit_mq
```

this worked for me, but let me know if you still face the same issue, I can look at it again and update the docs
