### ISSUE TITLE
Tesseract Worker with support Hindi, English, Tamil, Telugu

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#322]
Feluda has a `operator` that extracts text from images (OCR) using Tesseract. 
- The operator can be found here - detect_text_in_image_tesseract - https://github.com/tattle-made/feluda/blob/main/src/core/operators/detect_text_in_image_tesseract.py

Currently the operators supports extraction of text in English and Hindi language. 

### The task :-
1. Add support for Tamil and Telugu languages to the operator
2. Write a Worker for the Tesseract operator 

### What is a worker?
Workers are used to deploy operators at scale. They bring all the core parts of Feluda like `Store`, `Queue` and `Operators` together. Worker picks up a media file from `Queue` and uses `Operators` to analyse that media file. It then stores the analyzed data (output of operators in vector form) in Elasticsearch and sends a report containing the results back to the `Queue`.

A detailed documentation of the workers can be found [here](https://github.com/tattle-made/feluda/wiki/Workers)

All the worker files can be found at src/worker/ folder.

## Expected Outcome
- Modify the Tesseract Operator to support Tamil and Telugu. 
- Write worker for the Tesseract operator
  - Create necessary Dockerfiles
  - Create worker and worker payload writer files
- Document the Worker on the Wiki

This issue can also be split into 2 issues depending on the time needed to be spent on this.

**Comment by plon-Susk7** [comment]
Hey @aatmanvaidya , can I work on this issue?

**Comment by aatmanvaidya** [comment]
hi @plon-Susk7 , yes please feel free to take it up!

The current requirement and what would be good to have is adding support to the `operator` for Tamil and Telugu. 
So for now, let's keep the scope of the issue just to modify the `operator` and not implement the `worker`.
