### ISSUE TITLE
Evaluate similarity or clustering algorithms for video files

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/feluda#356]
Evaluate similarity or clustering algorithms for video frames. Finalize Sampling Strategy for videos.

**Comment by Snehil-Shah** [comment]
Hi.

**Comment by aatmanvaidya** [comment]
- [ ] Try out more Video Models for Embedding
- [ ] Try self-supervised clustering algorithms
- [ ] Do a review of lit for video pre-processing. Read up on better sampling strategies.

**Comment by aatmanvaidya** [comment]
@Snehil-Shah this is that kaggle competition I was talking about - https://www.kaggle.com/c/nfl-health-and-safety-helmet-assignment/discussion/285112

they have used k-means clustering for a different use case, do see if this helps you out

**Comment by aatmanvaidya** [comment]
- [ ] run video models on dataset and visualize using t-SNE, also do k-means clustering
- [ ] implement sampling strategies for video.

**Comment by aatmanvaidya** [comment]
- [ ] read and review sampling strategies
- [ ] Explore - closer frames as input, input higher moving frames etc. 
- [ ] how to select better n key frames.

**Comment by aatmanvaidya** [comment]
Notes - Jul 15
- extract keyframes from ffmpeg and then do QR

TODO
- [ ] Profile the CLIP embedding model. 
- [ ] keep experimenting with more sampling strategies. 
- [ ] collect dataset of low-quality videos in Indian Languages.
