### ISSUE TITLE
Use AudioVec Operator for Clustering Audio

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#361]
- [ ] Setup Feluda
- [ ] Convert video files to audio
- [ ] Try out Feluda AudioVec (or something you like) and use t-SNE (or other approaches) to evaluate clustering visually
   - can do this in a jupyter notebook and show results
- [ ] Look at other pre-trained models to convert audio files to embeddings.

**Comment by aatmanvaidya** [comment]
assigning this issue to @Chaithanya512

**Comment by aatmanvaidya** [comment]
A possible dataset to use - https://www.kaggle.com/datasets/mmoreaux/environmental-sound-classification-50?select=esc50.csv

**Comment by dennyabrain** [comment]
@Chaithanya512 can you comment on the issue so we can assign it to you?

**Comment by Chaithanya512** [comment]
Hi, thank you for the information.

**Comment by aatmanvaidya** [comment]
- [ ] Setup Feluda and run tests for AudioVecEmbedding Operator
- [ ] Collect a dataset of 150-200 Audio Files
- [ ] Run Feluda AudioVec Operator on a the dataset, reduce dimensions using t-SNE and do a visual plot - This will act as a baseline for us
- [ ] Try out different Embedding Models

**Comment by Chaithanya512** [comment]
Hi, 

Status:
- Had set-up feluda and ran tests for AudioVec Operator. 
- Curated a dataset by selecting 200 audio files from the environmental dataset. The original dataset contains 50 classes and 40 audio files for each class, I selected 10 random classes and gathered 20 files from those classes (10*20) + 114 audio files generated from Youtube videos. The total dataset contains 314 audio files.
- Tested AudioVec Operator on the dataset, reduced dimensions using t-SNE, and visualized using plotly. Also, tested the original dataset (all 2000 files) using AudioVec Operator.
- Tried out OpenL3 embedding model.  

[Google Colab Link](https://colab.research.google.com/drive/1lBrWCyUsuCSTOEUUqDwfc6FzpQWO0ETt?usp=sharing)

**Comment by aatmanvaidya** [comment]
- [ ] play the audio from the plot in colab
- [ ] try out more embedding models - AST
- [ ] do a review of lit for any video based transformer models are trained on audio

**Comment by aatmanvaidya** [comment]
google experiment clustering code - https://github.com/googlecreativelab/aiexperiments-drum-machine

**Comment by Snehil-Shah** [comment]
Recently found this audio embedding model called VGGish pre-trained by google. ([[1](https://github.com/tensorflow/models/blob/master/research/audioset/vggish/README.md)], [[2](https://www.kaggle.com/models/google/vggish/)], [[3](https://v-iashin.github.io/video_features/models/vggish/)]). Sharing here FWIW

**Comment by aatmanvaidya** [comment]
@Snehil-Shah thanks for sharing, looks interesting, @Chaithanya512 do try implementing it, I have found a direct PyTorch implementation of it - https://github.com/harritaylor/torchvggish/tree/f70241ba, you can download the model from PyTorch Hub. (this should hopefully simplify things for you)

I am also sharing some other audio embedding models I found
Note - this is just a dump of things I am finding, no pressure to try out everything, you can evaluate and take a call on what to try/ not try. 
1. [CLAP: Learning Audio Concepts From Natural Language Supervision](https://arxiv.org/abs/2206.04769) - [official code](https://github.com/LAION-AI/CLAP), [Hugging Face](https://huggingface.co/docs/transformers/en/model_doc/clap), [Microsoft python library](https://github.com/microsoft/CLAP).
2. [AST: Audio Spectrogram Transformer](https://arxiv.org/abs/2104.01778) - [Hugging Face](https://huggingface.co/docs/transformers/en/model_doc/audio-spectrogram-transformer)
3. [AI4Bharat IndicWav2Vec](https://ai4bharat.iitm.ac.in/indicwav2vec/) - this model is specific for speech thought (but do read up more on this) - [official code](https://github.com/AI4Bharat/IndicWav2Vec)
4. [HuBERT](https://arxiv.org/abs/2106.07447) - [Hugging Face](https://huggingface.co/docs/transformers/en/model_doc/hubert)
5. [Qwen-Audio: Advancing Universal Audio Understanding via Unified Large-Scale Audio-Language Models](https://arxiv.org/pdf/2311.07919) - [Hugging Face](https://huggingface.co/Qwen/Qwen-Audio), [sample code](https://github.com/prdeepakbabu/Qwen-AudioFM/tree/4c83ca80746a98a7a288b76b0e2afb05a35a448a)
6. [L3-Net Deep Audio Embeddings](https://arxiv.org/abs/2205.07682) - [code](https://github.com/marl/l3embedding?tab=readme-ov-file) - this looks built-on/ similar to VGGish that @Snehil-Shah shared. 
7. [COLA: Contrastive learning of general purpose audio representations](https://arxiv.org/abs/2010.10915) - [blog](https://towardsdatascience.com/paper-summary-implementation-contrastive-learning-of-general-purpose-audio-representations-f4e3cc06fcf7), [code](https://github.com/google-research/google-research/tree/master/cola), [pytorch code](https://github.com/CVxTz/COLA_pytorch)
8. [SurfPerch](https://www.kaggle.com/models/google/surfperch) - more for environment sounds from a cursory reading. 

Let me know if I can help out in any other way!

**Comment by Chaithanya512** [comment]
sure, thank you for sharing the embedding models. I will look into these.

**Comment by aatmanvaidya** [comment]
- AST performed better than Feluda AudioVec. 

- [ ] Let's keep trying out more transformer based/ CNN ensemble based models
- [ ] Evaluate clustering results

**Comment by Chaithanya512** [comment]
Updated Notebook: https://colab.research.google.com/drive/1lBrWCyUsuCSTOEUUqDwfc6FzpQWO0ETt?usp=sharing

- Implemented KMeans Clustering on AudioVec Operator embeddings.
- Evaluated Audio Spectrogram Transformers (AST), VGGish, HuBERT.

Comments: AST performs better as of now, AudioVec Operator with KMeans also shows good results.

**Comment by aatmanvaidya** [comment]
is something like this useful to us? -https://research.facebook.com/publications/wav2vec-2-0-a-framework-for-self-supervised-learning-of-speech-representations/
