### ISSUE TITLE
Run end-to-end clustering on custom Indian videos dataset

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#366]
@Snehil-Shah lets use this issue to document all the work you are doing on running a complete end-to-end clustering approach on the custom Indian videos dataset. 

Can you reply to the issue so that I can assign it to you!

**Comment by Snehil-Shah** [comment]
Comment

**Comment by Snehil-Shah** [comment]
[Clustering results on custom dataset](https://colab.research.google.com/drive/13zb3OeCcN0LasYvAOnqAdvqju_XU9ypc?usp=sharing)

**Comment by Snehil-Shah** [comment]
[Zero-shot classification results on custom dataset](https://colab.research.google.com/drive/1PzgcyqTZM_OUxELdFhGo32xFR4h0Iezo?usp=sharing)

**Accuracy**: 76-82% (check notebook to see how this bound is calculated)

This accuracy is really really good given there was **no additional training** done on our custom dataset (consisting of various *indian-context* videos of varied lengths and qualities).
