### ISSUE TITLE
Create a Worker for Clustering Media

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#378]
Details of clustering worker are documented here - https://github.com/tattle-made/feluda/wiki/Clustering-Spec-WIP#clustering-worker

This worker will support both audio and video modality.

**Comment by aatmanvaidya** [comment]
@Chaithanya512 @Snehil-Shah can you reply to this issue, I will assign it to you!

**Comment by Chaithanya512** [comment]
Hi

**Comment by aatmanvaidya** [comment]
issue resolved in - https://github.com/tattle-made/feluda/pull/379
