### ISSUE TITLE
Finalize Public API

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/feluda#409]
### Overview
We have to finalize the public touchpoints for feluda. The two touchpoints are 
1. the python code written while using feluda
2. syntax of the config.yml files

Ideally the python code to use feluda should be minimal and intuitive even for non developers.
Something like
```python
import Feluda

feluda = Feluda("config-server.yml")
feluda.init()
feluda.start()
```

The `config.yml` file is where you declare the operators, store etc that you require. We need to ensure that the syntax of the various configuration objects is consistent and there's error handling and helpful error messages in place for malformed config files.

The other thing to standardize would be how operators are used within the user's python code. Currently we have the following ways : 
1. `from core.operators import media_file_hash` and then using `media_file_hash.run(media)`
2. `feluda.operators["media_hash"].run(media)`

We can also consider using metaprogramming to enable `feluda.operators.media_hash.run(media)`. The meta programming approach might also provide suggestions and auto completion while developing, making the DX much smoother.

These are just a few on my mind, I am sure there's more things to standardize and finalize. The scope of this task is to list out all inconsistencies, prioritize and take a call on which need to be fixed and fix those.

I also think that working on https://github.com/tattle-made/feluda/issues/410 will help surface inconsistencies faster. So we could start by working on some recipes and then coming back to this issue.

**Comment by dennyabrain** [comment]
I was trying to use the resnet operator in its most barebones form to see which parts are essential and which can/should be moved to separate packages.

The code was organized like this. I created a `feluda_user` directory as sibling to the `feluda` directory. 
![feluda_user](https://github.com/user-attachments/assets/11b1813c-4ebd-491b-bf94-860998cd76cc)


`script.py` contains the following code to find the closest match of an image compared to a bunch of other images. 

```python
# NOT TO BE USED EVENTUALLY
import sys
sys.path.append('../feluda/src')

# IMPORTS
from sklearn.metrics.pairwise import cosine_similarity
from core.feluda import Feluda
from  core.models.media_factory import ImageFactory

feluda = Feluda("config.yml")
feluda.setup()
operator = feluda.operators.get()["image_vec_rep_resnet"]

embeddings = []

for i in range(6):
    file = ImageFactory.make_from_file_on_disk("image-"+str(i)+".png")
    embedding = operator.run(file)
    embeddings.append(embedding)

cos_sim = cosine_similarity(embeddings)
print(cos_sim)

sim_sorted_doc_idx = cos_sim.argsort()
# print(sim_sorted_doc_idx.shape)
print(sim_sorted_doc_idx[0][len(embeddings)-1])
match_ix = sim_sorted_doc_idx[0][len(embeddings)-2]

print("closest matches are image-0.png and image-"+str(match_ix)+".png")
```

To run this I had to run the following in the terminal. 
```sh
python -m venv .
source bin/activate
pip install -r requirements.txt

pip install PyYAML==6.0.2
pip install dacite==1.8.1
pip install pydub==0.25.1
pip install boto3==1.35.16
pip install wget==3.2
pip install werkzeug==3.0.3

pip install -r ../feluda/src/core/operators/image_vec_rep_resnet_requirements.txt
```

Ideally it should have been just the following lines : 
```sh
python -m venv .
source bin/activate
pip install -r requirements.txt
pip install -r ../feluda/src/core/operators/image_vec_rep_resnet_requirements.txt
```
Which eventually should become
```sh
python -m venv .
source bin/activate
pip install feluda
pip install feluda-op-vid-vec-resnet
```


The images used for this script were these
[images.zip](https://github.com/user-attachments/files/17620486/images.zip)

**Comment by dennyabrain** [comment]
@aatmanvaidya @plon-Susk7 can you see what we have to do to clean up the import statements for feluda.

Current API
```python
from core.feluda import Feluda
from  core.models.media_factory import ImageFactory
```
Preferred API
```python
from core import Feluda
# or 
import Feluda 


from core.models.media_factory import ImageFactory
```

**Comment by aatmanvaidya** [comment]
> @aatmanvaidya @plon-Susk7 can you see what we have to do to clean up the import statements for feluda.
> 
> Current API
> 
> ```python
> from core.feluda import Feluda
> from  core.models.media_factory import ImageFactory
> ```
> 
> Preferred API
> 
> ```python
> from core import Feluda
> # or 
> import Feluda 
> 
> 
> from core.models.media_factory import ImageFactory
> ```

yes I was thinking to take this up as the next step, in the current PR, we have a basic packaging into a wheel file working and some project structure setup, next we do this!

**Comment by aatmanvaidya** [comment]
new public API implemented in feluda v0.9.0 - [an example of how it looks and works](https://colab.research.google.com/drive/1LpTH2HNOAATQVuoOQRhN13T6qUQWCS6y?usp=sharing)

**Comment by aatmanvaidya** [comment]
Each operator should have 
- init() function
- run() function
- cleanup() function
- state() function - returns the internal state of the function, e.g. has the model been downloaded etc/

**Comment by aatmanvaidya** [comment]
here is what I think we can start of with, each operator will have:
- `initialise()` function
- `run()` function that looks like this
- `cleanup()` function
- `state()` function - returns the internal state of the function, e.g. has the model been downloaded etc

```python
run(file_path, *inputs, **kwargs)
```
and each operator will then have optional input arguments depending on its use case

since class inheritance is not possible it is difficult to have a parent base class from where each operator can inherit the structure, we will also add a validation class in `feluda`, that validates the structure

**Comment by dennyabrain** [comment]
I agree with your assessment. The config.yml thing was devised because I wanted an interface for non developers to quickly specify which features of feluda they need.
But few things have happened that have made the config.yml not as appealing 
1. We don't support pipelining or chaining of operators in config.yml. All business logic is anyways done in python.
2. All users of feluda or feluda like software seem to be python developers :P so the .yml thing just seems like a foreign implicit syntax thing they have to learn to use feluda.
3. As you pointed out we have packages now for operators


I noticed how you were creating string with content of .yml file in python code and that anyways seemed bad. When used like that, I would prefer specifying the configuration as a python dict anyways. Something to keep in mind if we continue with the .yml file spec.

I am ok with moving to a solution that doesn't use the config.yml. Do think of the changes needed to be made to feluda core.
Right now we pass initialisation parameters for every operator in the .yml file. We will need to make the developer do that in python

**Comment by aatmanvaidya** [comment]
some notes from our conversations -

Here are the final considerations and changes we discussed.  
1. Make `feluda` core lean
   - have separate feluda versions like `feluda[all]`, `feluda[video]` and `feluda[audio]`
   - these versions will make sure that only certain action related
2. `feluda` will be a dependency for each operator
3. Remove config and refactor how operators will be imported and used   - this means that each operator should be a class will follow the structure listed here - https://github.com/tattle-made/feluda/issues/409#issuecomment-2942821249
   - this means that we should add a `BaseOperator` class inside feluda core. This class will be inherited by all operators. 
4. Refactor how operators are imported and installed. below is an example
install all the Feluda operators like this
```sh
pip install feluda
pip install feluda-vid-vec-rep-clip
pip install cluster-embeddings
```
and then import them in the code like this
```py
from feluda import Feluda
from feluda.operators import VidVecRepClip
from feluda.operators import ClusterEmbeddings
```

**Comment by Hanzala89** [comment]
Final API
from feluda import Feluda

# one-liner setup
feluda = Feluda("config.yml").start()

# discover operators
print(feluda.list_operators())

# operator usage
result = feluda.operators.media_hash.run("file.png")


Implimentation 

class OperatorAccessor:
    def __init__(self, operators_dict):
        self._operators = operators_dict

    def __getattr__(self, name):
        if name in self._operators:
            return self._operators[name]
        raise AttributeError(
            f"Operator '{name}' not found. "
            f"Available: {list(self._operators.keys())}"
        )

class Feluda:
    def __init__(self, config_file):
        self.config_file = config_file
        self.operators = {}

    def start(self):
        self._load_config()
        self.operators = OperatorAccessor(self.operators)
        return self

    def list_operators(self):
        return list(self.operators._operators.keys())

**Comment by Hanzala89** [comment]
Final Api 

from feluda import Feluda
feluda = Feluda("config.yml").start()
print(feluda.list_operators())
result = feluda.operators.media_hash.run("file.png")


Implementation

class OperatorAccessor:
    def __init__(self, operators_dict):
        self._operators = operators_dict

    def __getattr__(self, name):
        if name in self._operators:
            return self._operators[name]
        raise AttributeError(
            f"Operator '{name}' not found. "
            f"Available: {list(self._operators.keys())}"
        )

class Feluda:
    def __init__(self, config_file):
        self.config_file = config_file
        self.operators = {}

    def start(self):
        self._load_config()
        self.operators = OperatorAccessor(self.operators)
        return self

    def list_operators(self):
        return list(self.operators._operators.keys())
