### ISSUE TITLE
python profiling for the tesseract operator

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#42]
do a python profiling for the tesseract operator
- look at the memory usage
- load testing

how does memory usage (RAM) go up?

`profiling`
- https://docs.python.org/3/library/profile.html
- https://realpython.com/python-profiling/
- https://roman.pt/posts/python-performance-profiling/
- https://www.turing.com/kb/profiling-python-code
- https://betterprogramming.pub/a-comprehensive-guide-to-profiling-python-programs-f8b7db772e6
- how to understand the output of `cProfile`?
   - https://stackoverflow.com/questions/3898266/what-is-this-cprofile-result-telling-me-i-need-to-fix
   - https://stackoverflow.com/questions/38225615/how-to-interpret-the-results-of-profiling
- `flame-graph` - https://pyflame.readthedocs.io/en/latest/usage.html

`memory profiling`
- https://docs.python.org/3/library/tracemalloc.html
- https://github.com/pythonprofilers/memory_profiler
- https://stackoverflow.com/questions/552744/how-do-i-profile-memory-usage-in-python

`load-testing`
- https://stackoverflow.com/questions/5103614/load-test-for-a-web-server
- https://wiki.python.org/moin/PythonTestingToolsTaxonomy#Web_Testing_Tools
- https://stackoverflow.com/questions/35024585/performance-load-testing-tools-to-test-rest-apiheadless-rest-endpoint-without
- CPU load check
   - https://medium.com/@tferreiraw/performing-load-tests-with-python-locust-io-62de7d91eebd
   - https://dev.to/jankaritech/performance-testing-with-locust-04-interpret-the-results-3hco
   -

**Comment by aatmanvaidya** [comment]
https://locust.io/ - for load testing in python

**Comment by aatmanvaidya** [comment]
size of tesseract is somewhere between 5-20 MB.

**Comment by dennyabrain** [comment]
it must also depend on what model you include, right? single language, multilanguage? 
I also supposed models are of different sizes depending on their training corpus size?

**Comment by aatmanvaidya** [comment]
> it must also depend on what model you include, right? single language, multilanguage? I also supposed models are of different sizes depending on their training corpus size?

yes, I am still figuring it out, I will add more details to the above comment with sources
