### ISSUE TITLE
Test cases missing for text_vec_rep_paraphrase_lxml operator

### ISSUE THREAD

**Issue by plon-Susk7** [tattle-made/feluda#421]
The test cases for above mentioned operator is missing in src/core/operators.

**Comment by adoo100** [comment]
Hi @plon-Susk7 I would be open to working on this if it is still available, just let me know :)

**Comment by plon-Susk7** [comment]
hey @adoo100 , feel free to take this up. Let me know if I can assist you with anything.

**Comment by adoo100** [comment]
@plon-Susk7 I believe that will do it, let me know if it is ready to merge

**Comment by plon-Susk7** [comment]
@aatmanvaidya

**Comment by aatmanvaidya** [comment]
resolved in https://github.com/tattle-made/feluda/pull/446
