### ISSUE TITLE
fix: known bugs and issues

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#49]
- [x] in the Elasticsearch test - `test_es_vec.py` - fix `es.refresh()` and `es.delete_indices()`
- [x] in the Dockefile we are installing using `requirements.txt`, which assumes someone's already generated it. this `requirements.in` -> `requirements.txt` transformation should happen in the Dockerfile too
- [ ] in `test_index_api_as_client.py` - fix when POST request for image and video when `multipart/form-data` is sent. Do not send the header for this request. fix the `fromRequestPayload()`function
- [ ] in `test_index_api_as_client.py` -  the `testIndexVideo()` is passing the test, but not returning an ID
- [x] in `test_search_api_as_client.py` fix `testIndexVideo()`
- [x] move all the tests to a single folder

**Comment by duggalsu** [comment]
hey @aatmanvaidya , regarding this
```
in the Dockefile we are installing using requirements.txt, which assumes someone's already generated it. this requirements.in -> requirements.txt transformation should happen in the Dockerfile too
```
We should not create `requirements.txt` within docker.
`requirements.in` is similar to `package.json`
`requirements.txt` is similar to `package-lock.json`

We will be maintaining feluda core `requirements.txt` to be compatible with the `requirements.txt` for operators, which may mean force modifying some dependencies in either `requirements.[in/txt]`

The docker should directly install all existing `requirements.txt` as a source of verified stable package versions

**Comment by aatmanvaidya** [comment]
I have made progress with fixing the `fromRequestPayload()` in the `index handler`, but it hasn't been fixed yet.
